---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
spec:
  template:
    spec:
      containers:
        - name: forgejo-engine
          env:
            - name: APP_NAME
              value: Ze Git
