---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-engine-data
spec:
  storageClassName: manual
  accessModes: [ReadWriteOnce]
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
