---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
  labels:
    app: forgejo
    role: engine
    protocol: ssh
spec:
  type: LoadBalancer
  selector:
    app: forgejo
    role: engine
  ports:
    - name: sshgit
      protocol: TCP
      port: 22
      targetPort: 22
