---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  labels:
    app: forgejo
    role: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
      role: engine
  template:
    metadata:
      labels:
        app: forgejo
        role: engine
    spec:
      serviceAccountName: forgejo-service-account
      containers:
        - name: forgejo-engine
          image: codeberg.org/forgejo/forgejo:7.0
          ports:
            - name: ssh
              containerPort: 22
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /data
            - name: config
              mountPath: &config_file_path /data/gitea/conf/app.ini
              subPath: &config_file_subpath app.ini
              readOnly: true
            - name: secret-key
              mountPath: /etc/forgejo/secret_key
              subPath: &secret_key_subpath secret_key
              readOnly: true
            - name: internal-token
              mountPath: /etc/forgejo/internal_token
              subPath: &internal_token_subpath internal_token
              readOnly: true
          env:
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: TMPDIR
              value: /tmp/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_APP_INI
              value: *config_file_path
          startupProbe: &probe
            failureThreshold: 10
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          readinessProbe:
            <<: *probe
            initialDelaySeconds: 60
          livenessProbe:
            <<: *probe
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {} # To override in more specific scenarios
        - name: config
          configMap:
            name: forgejo-config
            items:
              - key: forgejo.ini
                path: *config_file_subpath
        - name: secret-key
          secret:
            secretName: forgejo-secrets
            items:
              - key: secret_key
                path: *secret_key_subpath
        - name: internal-token
          secret:
            secretName: forgejo-secrets
            items:
              - key: internal_token
                path: *internal_token_subpath
