---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
spec:
  template:
    spec:
      containers:
        - name: forgejo-engine
          env:
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: postgres
            - name: FORGEJO__database__NAME
              value: forgejo
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: FORGEJO__database__PATH
              $patch: delete
