---
apiVersion: v1
kind: Service
metadata:
  name: postgres-forgejo
  labels:
    app: forgejo
    role: database
spec:
  type: LoadBalancer
  selector:
    app: forgejo
    role: database
  ports:
    - name: postgres
      port: 5432
