---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-engine-data
spec:
  storageClassName: local-path
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
