apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: csi-driver-smb
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    namespace: kube-system

secretGenerator:
  - name: smbcreds
    namespace: kube-system
    env: smbcreds.env
    options:
      disableNameSuffixHash: true

resources:
  - ./storage-class.yaml
