apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

secretGenerator:
  - name: parent-secrets
    namespace: netdata
    env: parent-secrets.env
  - name: child-secrets
    namespace: netdata
    env: child-secrets.env

patches:
  - path: ./patchParentDeployment.yaml
  - path: ./patchChildDaemonSet.yaml

helmCharts:
  - name: netdata
    repo: https://netdata.github.io/helmchart/
    namespace: netdata
    valuesInline:
      image:
        tag: edge
      restarter:
        enabled: true
      parent:
        env:
          DO_NOT_TRACK: 1
        claiming:
          enabled: true
      child:
        env:
          DO_NOT_TRACK: 1
        claiming:
          enabled: true
