apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

secretGenerator:
  - name: parent-secrets
    env: parent-secrets.env
  - name: child-secrets
    env: child-secrets.env

patches:
  - path: ./patchReferenceKustomizeSecret.yaml

helmCharts:
  - name: netdata
    repo: https://netdata.github.io/helmchart/
    namespace: tools
    valuesInline:
      image:
        tag: edge
      restarter:
        enabled: true
      parent:
        env:
          DO_NOT_TRACK: 1
        claiming:
          enabled: true
      child:
        env:
          DO_NOT_TRACK: 1
        claiming:
          enabled: true
