name: Deploy Dev
on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "~1.22"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/go.sum"
      - run: go mod download
        working-directory: ./deploy
      - run: go install github.com/pulumi/crd2pulumi@latest
        working-directory: ./deploy
      - run: go generate ./...
        working-directory: ./deploy
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: raz_algethi/homelab/dev
          work-dir: ./deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
