name: Deploy Live
on:
  push:
    branches:
      - main

jobs:
  Deploy-Live:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: nicknovitski/nix-develop@v1
      - run: yarn install
      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: raz_algethi/homelab/live
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
